### ISSUE TITLE
Slider slides fastly while in autoplay

### ISSUE THREAD

**Issue by marviljoy** [austenpayan/skippr#1]
Without the effect in speed control, slider moves outside the container very fast and shows the background. 

Suppose we have only 2 slides, also we have the default setting for the slider
But, while doing sliding loop continuesly, slider moves faster and faster again.
This causes the slider moves outside the div and shows the background.

Please view the attached screenshot, we have the white background 

![issue](https://cloud.githubusercontent.com/assets/2322781/3172114/50addb3e-ebd0-11e3-93cd-f3f3c52bc616.png)

**Comment by flamingoezz** [comment]
Was there ever a resolution to this issue?  I'm still having issue with the consistency of time a slide displays.  Slide 1 may display for 5 seconds, while the second slide may appear for 2 or so.  I do have autoPlayDuration set.

**Comment by stabeebit** [comment]
If I remember correctly I just ended up using a different image slider all together

**Comment by austenpayan** [comment]
Sorry for the delay guys. I found a fix, there were duplicate timers firing off during certain window events that was causing the strange behavior during autoplay.
