### ISSUE TITLE
Last layer blank

### ISSUE THREAD

**Issue by danilinked** [austenpayan/skippr#11]
Hi Austen,

I applied your fantastic slide in one of my site, and everythink looks perfect but, for example if I have 5 div  (slides) then there are one more appear in blank. I don't don't no if it's maybe some conflict with other jquery. I thought maybe is some difference between <script src="//code.jquery.com/jquery-1.11.1.min.js"></script> and script src="//code.jquery.com/jquery-1.11.0.min.js"></script>

If you are not so busy tell me something. 

Looking forward to hearing from you. Thanks

**Comment by austenpayan** [comment]
Hello! What browser and OS do you use?

**Comment by austenpayan** [comment]
I looked at your code from the email you sent me, it looks like there is an unnecessary <p> tag inside your target element. Try removing that and see what happens.

![screen shot 2015-01-27 at 1](https://cloud.githubusercontent.com/assets/3936068/5923585/72eb70a0-a609-11e4-8fe2-a2a32397b96c.png)

**Comment by danilinked** [comment]
Always a stupid think, :) Thank you for your help. I appreciate the fast reply and mostly your help. Keep in contact Austen ;)
