### ISSUE TITLE
Skippr Slider issue

### ISSUE THREAD

**Issue by iontorres** [austenpayan/skippr#12]
hi Austen, I have an issue in my slider autoplay function. It's works perfect at the time you enter to the site but suddently the autoplay function crashes it. I could fix it setting my autoplay as "false" but i don't want to.

Here's my code:
                     [div class="contenedor-slider"]
                     [div id="main-slider"]
                      <?php while ($row = mysql_fetch_array($query_slider)){
                         echo '[div style="width:100%;"]';
                             echo '[img style="width:100%;" src="img/slider/'. $row["foto"]. '"]';
                             echo '[div class="blue_cover"][/div]';
                             echo '[div class="txt-banner"][h3]'.$row["txt"].'[/h3][p]'.$row["txtsub"].'[/p][/div]';
                         echo '[/div]';
                        } 
                    ?>
                    [/div]
                    [/div]

     <script type="text/javascript">

            $(document).ready(function(){
                $("#main-slider").skippr({
                    transition: 'slide',
                    speed: 1200,
                    easing: 'easeOutQuart',
                    childrenElementType: 'div',
                    arrows: false,
                    autoPlay: true,
                    navType: 'bubble',
                    keyboardOnAlways: false,
                    autoPlayDuration: 3500
                });
            });

        </script>

And here's the example
http://www.marvi.com.mx/09/

Any idea what might be the problem?

**Comment by austenpayan** [comment]
I think I do have an idea. There seems to be a problem with multiple intervals overriding eachother. I have seen this happen on a few other occasions, I will move it higher on my priorities list and try to find a fix. Ill let you know here when that happens!

**Comment by iontorres** [comment]
Thank you so much! (:

**Comment by morgzz** [comment]
Any update on this, I too am experiencing this issue in Chrome.

**Comment by austenpayan** [comment]
Sorry for the delay guys. I found a fix, there were duplicate timers firing off during certain window events that was causing the strange behavior during autoplay.
