### ISSUE TITLE
Problems in Firefox

### ISSUE THREAD

**Issue by wudges** [austenpayan/skippr#8]
Hi,

Great script, really like the look of it!

One problem I'm finding, is that in Firefox when the slider is set to autoPlay: true, the images play in the wrong order.

With 5 images I'm finding it goes 1-3-5-2-4

Is there a workaround or update due soon that will sort this. It happens in your demo too.

Thanks in advance :)

**Comment by wudges** [comment]
Hi, I still haven't been able to find a solution to this problem. Do you have any ideas?
Thanks!

**Comment by garudacrafts** [comment]
I'm also seeing the same behavior in Firefox when autoplay is enabled: it skips to every other image, with a flash of the skipped image.

**Comment by austenpayan** [comment]
Sorry for the delay guys. I found a fix, there were duplicate timers firing off during certain window events that was causing the strange behavior during autoplay.
